# target programming lamguage
language: java

# JDK versios support
jdk:
  - oraclejdk7
  - oraclejdk8
addons:
  postgresql: "9.4"
sudo: required

services:
  - postgresql

test:
  adapter: postgresql
  database: teste2
  username: postgres
  password: admin123

# run tests, findbugs, pmd and friends using Ant, Maven or Gradle
script: ant test

before_script:
  - psql -c "create database teste2;" -U postgres
  - psql -c "create schema trabalho;" -U postgres
  - pg_restore -U postgres -d teste2 -1 -f BancoVendas.backup
